openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8090
paths:
  /example/get-test:
    get:
      operationId: getTest
      responses:
        "202":
          content:
            '*/*':
              schema:
                type: string
          description: Accepted
      tags:
      - rest-api-example
      x-accepts: '*/*'
  /example:
    get:
      operationId: ping
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - rest-api-example
      x-accepts: '*/*'
  /example/post-test:
    post:
      operationId: postTest
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - rest-api-example
      x-contentType: application/json
      x-accepts: '*/*'
  /login/login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginData'
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProfileData'
          description: OK
      tags:
      - rest-api-login-example
      x-contentType: application/json
      x-accepts: '*/*'
components:
  schemas:
    LoginData:
      example:
        password: password
        username: username
      properties:
        username:
          type: string
        password:
          type: string
      type: object
    ProfileData:
      example:
        firstName: firstName
        lastName: lastName
        active: true
        username: username
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        active:
          type: boolean
      type: object

